version: '2'
services:

  compliance:
    build: .
    volumes:
     - ./:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - TWITTER_GNIP_USERNAME=${GNIP_USERNAME}
     - TWITTER_GNIP_PASSWORD=${GNIP_PASSWORD}
     - TWITTER_COMPLIANCE_URL=${COMPLIANCE_URL}
     - TWITTER_COMPLIANCE_S3_KEY=${S3_KEY}
     - TWITTER_COMPLIANCE_S3_SECRET=${S3_SECRET}
     - TWITTER_COMPLIANCE_S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - TWITTER_COMPLIANCE_S3_REGION_NAME=${S3_REGION_NAME}
    command: "lein trampoline run"
